name: qrcodegenerator
description: a qr code generator .

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  file_picker: ^6.1.1
  file_utils: ^1.0.1

  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.1.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  path: ^1.8.3
  path_provider: ^2.1.2
  pretty_qr_code: ^3.2.1
  provider: ^6.1.1
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  watcher: ^1.1.0
  connectivity_plus: ^5.0.2
  flutter_native_splash: 2.3.7
  app_tutorial: ^1.0.6
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
